#!/usr/bin/env bash


INSTALL_DIR="$HOME/.local/bin/"

#####################################################################################

venvCreate ()
{
    virtualenv --clear -p python2 --system-site-packages .venv
}

venvActivate ()
{
    . .venv/bin/activate
}

absPath() {

    readlink -f "$@"
}

makeLink() {

    ln -svf "$(absPath .venv)/bin/$1" "$2"
}

#####################################################################################
## main

venvCreate

venvActivate

pip install .

echo

makeLink _pidginCompleteBuddy   "$INSTALL_DIR"
makeLink pidginMsg              "$INSTALL_DIR"
makeLink pidginQuickLaunch      "$INSTALL_DIR"
