#!/usr/bin/env bash


INSTALL_DIR="$HOME/.local/bin/"

#####################################################################################

venvCreate ()
{
    local interpreter="$1"

    virtualenv --clear -p "$interpreter" --system-site-packages .venv
}

venvActivate ()
{
    . .venv/bin/activate
}

absPath() {

    readlink -f "$@"
}

makeLink() {

    ln -svf "$(absPath .venv)/bin/$1" "$2"
}

#####################################################################################
## main

interpreter="${1-python2}"

venvCreate "$interpreter"

venvActivate

pip install .

echo

makeLink _pidginCompleteBuddy   "$INSTALL_DIR"
makeLink pidginMsg              "$INSTALL_DIR"
makeLink pidginQuickLaunch      "$INSTALL_DIR"
